name: hipool
channels:
  - conda-forge
  - pytorch
dependencies:
  - huggingface::transformers
  - jaxtyping
  - jupyterlab
  - networkx
  - numpy
  - pandas
  - pip
  - pytest
  - python
  - pytorch::pytorch
  - scikit-learn
  - pip:
    - torch_geometric
    - torcheval
    - typeguard