name: hipool
channels:
  - nvidia # For pytorch's GPU dependencies
dependencies:
  - huggingface::transformers
  - ipywidgets
  - jsonlines
  - jupyterlab
  - networkx
  - numpy
  - pandas
  - pip
  - pyg::pyg
  - pytest
  - pytest-cov
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - scikit-learn
  - tqdm
  - pip:
    - jaxtyping 
    - torcheval
    - typeguard