name: hipool
channels:
  - nvidia # For pytorch's GPU dependencies
dependencies:
  - huggingface::transformers
  - networkx
  - numpy
  - pandas
  - pyg::pyg
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.7
  - scikit-learn